services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/debian/ToneBot/data:/app/Discord/data
      - /media/appdata/ToneBot/songs:/app/Discord/data/songs
      - /etc/localtime:/etc/localtime
    restart: always
