services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/debian/ToneBot/:/home/discord/Discord/
      - /media/archive/Discord/songs:/home/discord/Discord/songs
      - /etc/localtime:/etc/localtime
    restart: always
