services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/pi/Discord:/home/discord/Discord
      - /media/pi/Archive/Discord/songs:/home/discord/Discord/songs
      - /etc/localtime:/etc/localtime
    restart: always
